-- Vocabulary becomes per-user: every card belongs to a user. Shared words are handled by
-- copy-on-add (see CardGenerationService) so identical content is generated by the LLM only once.

ALTER TABLE cards ADD COLUMN owner_id BIGINT REFERENCES users(id) ON DELETE CASCADE;

-- Backfill any existing cards to the first admin (the original seed owner).
UPDATE cards SET owner_id = (SELECT id FROM users WHERE is_admin = true ORDER BY id LIMIT 1)
WHERE owner_id IS NULL;
-- Fallback (no admin present): the lowest user id, so the NOT NULL below cannot fail.
UPDATE cards SET owner_id = (SELECT id FROM users ORDER BY id LIMIT 1)
WHERE owner_id IS NULL;

ALTER TABLE cards ALTER COLUMN owner_id SET NOT NULL;

-- Slug is unique per owner (not globally) so two users can each own the same word.
ALTER TABLE cards DROP CONSTRAINT cards_slug_key;
ALTER TABLE cards ADD CONSTRAINT cards_owner_slug_key UNIQUE (owner_id, slug);

CREATE INDEX idx_cards_owner ON cards (owner_id);
